#!/bin/bash
# QUILT2 SLURM config defaults (mirrors Step1C pattern)
# Override via environment as needed.

# Account/partition
QUILT2_ACCOUNT="${QUILT2_ACCOUNT:-${PIPELINE_SLURM_ACCOUNT:-a_qaafi_cas}}"
QUILT2_PARTITION="${QUILT2_PARTITION:-${SLURM_PARTITION:-general}}"
QUILT2_QOS="${QUILT2_QOS:-${SLURM_QOS:-}}"

# Resources
QUILT2_NODES="${QUILT2_NODES:-1}"
QUILT2_NTASKS="${QUILT2_NTASKS:-1}"
QUILT2_CPUS_PER_TASK="${QUILT2_CPUS_PER_TASK:-2}"
QUILT2_MEMORY="${QUILT2_MEMORY:-8G}"
QUILT2_TIME_LIMIT="${QUILT2_TIME_LIMIT:-72:00:00}"

# Array limit (max tasks submitted even if manifest longer)
QUILT2_ARRAY_MAX="${QUILT2_ARRAY_MAX:-${QUILT2_ARRAY_LIMIT:-0}}" # 0 = no cap
QUILT2_CONSTRAINT="${QUILT2_CONSTRAINT:-}"

get_quilt2_config() {
    cat <<EOF
ACCOUNT=${QUILT2_ACCOUNT}
PARTITION=${QUILT2_PARTITION}
QOS=${QUILT2_QOS}
NODES=${QUILT2_NODES}
NTASKS=${QUILT2_NTASKS}
CPUS=${QUILT2_CPUS_PER_TASK}
MEMORY=${QUILT2_MEMORY}
TIME=${QUILT2_TIME_LIMIT}
ARRAY_MAX=${QUILT2_ARRAY_MAX}
CONSTRAINT=${QUILT2_CONSTRAINT}
EOF
}
